---
- name: Build Docker image
  hosts: docker.local
  become: yes
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Build Docker image from Dockerfile
      become_user: root
      docker_image:
        name: kiranimg4:latest
        source: build
        build:
          pull: no
          path: /root/jenkins/
          dockerfile: Dockerfile

